# This is a basic workflow to help you get started with Actions

name: github pages update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  merge:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      # Runs a single command using the runners shell
      - name: cargo doc
        run: cargo doc --no-deps --all-features --release --all

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls
          cp -r target/doc ../gh-pages/
          cd ..
          git clone --single-branch --branch gh-pages https://github.com/mendelsshop/loading_bar.git
          ls
          cp -r loading_bar/target/doc ../gh-pages/
          git add -A
          git commit -m "Update docs"
